#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import root

g = 9.8

def fr(v, vc, vs, mu):
    return mu * np.tanh(v/vc) + v/vs * np.exp(-(v/vs)**2)

def vb(v, B, C, E, mu):
    return mu * np.sin(C * np.arctan(B*v) - E*((B*v) - np.arctan(B * v)))


# res = root(fr, 0.01, args=(0.01, 0.01, 0.16))
# print(res)
# quit()


v = np.linspace(-0.5, 0.5, 1000)
mu = 0.16
vc = 0.01
vs = 0.005663

B = 1.0e2
C = 1.0
E = -1.0e-3


plt.plot(v, fr(v, vc, vs, mu), label='fr paso 2')
plt.plot(v, vb(v, B, C, E, mu), label='velocity based - ec5)')
plt.legend()
plt.tight_layout()
plt.savefig('froce.pdf')
